spring.application.name=00-springboot-hello
logging.level.org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor=DEBUG


server.tomcat.threads.max=1
server.tomcat.accept-count=0
server.tomcat.connection-timeout=1ms

