
#spring.datasource.url=jdbc:mysql://localhost:3306/39prod?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=India@123

spring.h2.console.enabled=true

management.endpoints.web.exposure.include=*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.banner.location=classpath:banner-prod.txt